import { z } from "zod";

// B版：完整对象模型参考实现。

export const kinds = ["vfd","gfan","dp","vent","rev","lock","cargo","emg","gen","th","co2"] as const;
export type Kind = typeof kinds[number];
export const pressureModes = ["inflate","normal","wind1","wind2","wind3","rain","overpressure"] as const;
export type PressureMode = typeof pressureModes[number];
export const modeNames: Record<PressureMode,string> = { inflate:"初始充气",normal:"正常",wind1:"一阶抗风",wind2:"二阶抗风",wind3:"三阶抗风",rain:"雨雪",overpressure:"超压急停" };
export const modeTargets: Record<PressureMode,number> = { inflate:180,normal:180,wind1:200,wind2:240,wind3:280,rain:380,overpressure:0 };

type PointDef = { suffix:string; name:string; dataType:string; unit:string; rw:"R"|"W"|"RW"; sample:string };
type TypeDef = { name:string; prefix:string; hint:string; limit:number; points:PointDef[]; defaults:{ capacity:number;width:number;height:number;coefficient:number;opening:number }; abilities:string[]; dependencies:string[]; failure:string[]; thresholds:{key:string;name:string;min:number;max:number;default:number;unit:string}[]; behaviors:Record<PressureMode,string> };
const pts=(items:Array<[string,string,string,string,"R"|"W"|"RW",string]>):PointDef[]=>items.map(([suffix,name,dataType,unit,rw,sample])=>({suffix,name,dataType,unit,rw,sample}));
const fanBehavior:Record<PressureMode,string>={inflate:"按充气曲线渐进升压",normal:"变频调节维持设定压力",wind1:"按一阶设定值调节，禁止停机",wind2:"按二阶设定值调节，禁止停机",wind3:"全速运行，禁止停机",rain:"升至雨雪设定值",overpressure:"按急停策略停机"};
const onoffBehavior:Record<PressureMode,string>={inflate:"按系统加载序列待命",normal:"按系统容量需求投入",wind1:"容量不足时投入",wind2:"按加载序列投入",wind3:"全部投入运行",rain:"按雨雪策略投入",overpressure:"立即停机"};
const passive=(normal:string):Record<PressureMode,string>=>({inflate:"参与初始充气监测",normal,wind1:"参与一阶抗风监测",wind2:"参与二阶抗风监测",wind3:"参与三阶抗风监测",rain:"参与雨雪监测",overpressure:"参与超压急停监测"});
export const typeLibrary:Record<Kind,TypeDef>={
 vfd:{name:"变频风机",prefix:"VFD",hint:"30,000 m³/h · 16–50 Hz",limit:6,defaults:{capacity:30000,width:0,height:0,coefficient:0,opening:0},abilities:["启动｜前置：手动模式、无故障、变频就绪｜权限：R2以上｜二次确认：是","停止｜前置：手动模式、非大风工况｜权限：R2以上｜二次确认：是","调频｜区间：16–50 Hz｜权限：R2以上｜二次确认：否"],dependencies:["数据依赖 ← 差压变送器（读值参与内环调节）","联锁依赖 ← 门开到位（强制提频补压）","降级依赖 ← 压差数据 BAD（双表坏转固定频率）","影响 → 膜内差压 · 供风量 30,000 m³/h"],failure:["自身故障 → 下一台接管 + 重要级报警","依赖数据 BAD → 取另一只压表；双表坏转固定频率 + 紧急级报警","云端断连 → 不受影响，PLC 独立运行"],thresholds:[{key:"minHz",name:"最低频率",min:16,max:24,default:16,unit:"Hz"},{key:"maxHz",name:"最高频率",min:45,max:50,default:50,unit:"Hz"}],behaviors:fanBehavior,points:pts([["cmd","启停命令","BOOL","","W","事件"],["fb","运行反馈","BOOL","","R","1s"],["hz_sp","频率给定","REAL","Hz","W","1s"],["hz_fb","频率反馈","REAL","Hz","R","1s"],["fault","故障","BOOL","","R","事件"],["remote","远程就绪","BOOL","","R","1s"],["runtime","累计运行时间","DINT","h","R","60s"]])},
 gfan:{name:"工频风机",prefix:"GF",hint:"28,000 m³/h · 固定 50 Hz",limit:18,defaults:{capacity:28000,width:0,height:0,coefficient:0,opening:0},abilities:["启动｜前置：自动允许、无故障、驻留完成｜权限：R2以上｜二次确认：是","停止｜前置：容量预判通过、非强制运行｜权限：R2以上｜二次确认：是"],dependencies:["数据依赖 ← 系统容量需求","联锁依赖 ← 变频机组已到调节边界","影响 → 膜内差压 · 供风量 28,000 m³/h"],failure:["自身故障 → 跳过本机加载下一台 + 重要级报警","依赖数据 BAD → 保持当前状态 + 紧急级报警","云端断连 → 不受影响，PLC 独立运行"],thresholds:[],behaviors:onoffBehavior,points:pts([["cmd","启停命令","BOOL","","W","事件"],["fb","运行反馈","BOOL","","R","1s"],["fault","故障","BOOL","","R","事件"]])},
 dp:{name:"差压变送器",prefix:"DP",hint:"0–1000 Pa",limit:4,defaults:{capacity:0,width:0,height:0,coefficient:0,opening:0},abilities:["读取｜区间：0–1000 Pa｜权限：R1以上｜二次确认：否"],dependencies:["影响 → 变频内环、工况判定与报警"],failure:["自身故障 → 切换另一只压表","双表皆坏 → 固定频率降级 + 紧急级报警","云端断连 → 不受影响，PLC 独立运行"],thresholds:[{key:"range",name:"量程上限",min:600,max:1500,default:1000,unit:"Pa"}],behaviors:passive("双表取可信值参与压力闭环"),points:pts([["pv","差压值","REAL","Pa","R","1s"],["quality","数据质量","BYTE","","R","1s"],["fault","故障","BOOL","","R","事件"]])},
 vent:{name:"排风阀",prefix:"VENT",hint:"0.8 m² · 0–100%",limit:8,defaults:{capacity:0,width:0,height:0,coefficient:.8,opening:35},abilities:["调节开度｜区间：0–100%｜权限：R2以上｜二次确认：否","关闭｜前置：非换气强制｜权限：R2以上｜二次确认：是"],dependencies:["数据依赖 ← 当前压力工况","影响 → 等效泄漏面积最大 0.8 m²"],failure:["自身故障 → 关闭优先 + 重要级报警","依赖数据 BAD → 限制开度为 0%","云端断连 → 不受影响，PLC 独立运行"],thresholds:[{key:"opening",name:"正常最大开度",min:0,max:35,default:35,unit:"%"}],behaviors:{inflate:"强制 0%",normal:"最大开度 35%",wind1:"最大开度 30%",wind2:"强制 0%",wind3:"强制 0%",rain:"强制 0%",overpressure:"按急停泄压策略执行"},points:pts([["sp","开度给定","REAL","%","W","1s"],["fb","开度反馈","REAL","%","R","1s"]])},
 rev:{name:"旋转门",prefix:"REV",hint:"2.2×2.4 m · A≈0.16 m²",limit:4,defaults:{capacity:0,width:2.2,height:2.4,coefficient:.03,opening:0},abilities:["监测开闭｜前置：无｜权限：R1以上｜二次确认：否"],dependencies:["联锁依赖 → 开启时通知补压","影响 → 常态等效泄漏面积 0.16 m²"],failure:["自身故障 → 状态未知 + 重要级报警","依赖数据 BAD → 按开启状态保守计算","云端断连 → 不受影响，PLC 独立运行"],thresholds:[],behaviors:passive("常态微漏计入物理模型"),points:pts([["open","开启状态","BOOL","","R","事件"],["fault","故障","BOOL","","R","事件"]])},
 lock:{name:"气锁门",prefix:"LOCK",hint:"2.5×2.5 m · A≈0.31 m²",limit:4,defaults:{capacity:0,width:2.5,height:2.5,coefficient:.05,opening:0},abilities:["监测互锁｜前置：两扇门不得同时开｜权限：R1以上｜二次确认：否"],dependencies:["联锁依赖 ← 内外门互锁状态","影响 → 常态等效泄漏面积 0.31 m²"],failure:["自身故障 → 禁止另一扇门开启 + 紧急级报警","依赖数据 BAD → 按开启状态保守计算","云端断连 → 不受影响，PLC 独立运行"],thresholds:[],behaviors:passive("互锁通行并计入常态微漏"),points:pts([["open","开启状态","BOOL","","R","事件"],["interlock","互锁状态","BOOL","","R","事件"]])},
 cargo:{name:"物流门",prefix:"CARGO",hint:"4×4 m · 开启 A=5.60 m²",limit:3,defaults:{capacity:0,width:4,height:4,coefficient:.35,opening:0},abilities:["监测开闭｜前置：开启计时有效｜权限：R1以上｜二次确认：否","开启许可｜前置：压力补偿准备｜权限：R2以上｜二次确认：是"],dependencies:["联锁依赖 → 开启触发全力补压","影响 → 开启增加等效泄漏面积 5.60 m²"],failure:["自身故障 → 按开启状态计算 + 紧急级报警","依赖数据 BAD → 限制开启时长","云端断连 → 不受影响，PLC 独立运行"],thresholds:[{key:"openLimit",name:"最大开启时长",min:10,max:300,default:90,unit:"s"}],behaviors:passive("开启时触发严重泄压补偿"),points:pts([["cmd","开门许可","BOOL","","W","事件"],["open","开启状态","BOOL","","R","事件"],["timer","开启计时","DINT","s","R","1s"],["alarm","超时报警","BOOL","","R","事件"]])},
 emg:{name:"应急门",prefix:"EMG",hint:"1.2×2.1 m · 常闭监测",limit:6,defaults:{capacity:0,width:1.2,height:2.1,coefficient:.35,opening:0},abilities:["监测开闭｜前置：常闭｜权限：R1以上｜二次确认：否"],dependencies:["影响 → 开启增加等效泄漏面积 0.88 m²"],failure:["自身故障 → 状态未知 + 紧急级报警","依赖数据 BAD → 按开启状态保守计算","云端断连 → 不受影响，PLC 独立运行"],thresholds:[],behaviors:passive("常闭，仅监测异常开启"),points:pts([["open","开启状态","BOOL","","R","事件"]])},
 gen:{name:"发电机组",prefix:"GEN",hint:"120 kW · 备用供电",limit:2,defaults:{capacity:120,width:0,height:0,coefficient:0,opening:0},abilities:["启动｜前置：市电失电、油位正常｜权限：R2以上｜二次确认：是","停机｜前置：市电稳定、冷却完成｜权限：R2以上｜二次确认：是"],dependencies:["联锁依赖 ← 市电状态","影响 → 风机与控制系统备用供电"],failure:["自身故障 → 无电降级 + 紧急级报警","依赖数据 BAD → 禁止自动并网","云端断连 → 不受影响，PLC 独立运行"],thresholds:[{key:"capacity",name:"额定容量",min:80,max:400,default:120,unit:"kW"}],behaviors:passive("市电失电时按本地程序接管"),points:pts([["cmd","启停命令","BOOL","","W","事件"],["fb","运行反馈","BOOL","","R","1s"],["kw","输出功率","REAL","kW","R","1s"],["fuel","燃油液位","REAL","%","R","60s"],["fault","故障","BOOL","","R","事件"],["ready","并网就绪","BOOL","","R","1s"]])},
 th:{name:"温湿度传感器",prefix:"TH",hint:"温度 + 湿度",limit:6,defaults:{capacity:0,width:0,height:0,coefficient:0,opening:0},abilities:["读取｜温度与湿度｜权限：R1以上｜二次确认：否"],dependencies:["影响 → 环境超限提示、报表"],failure:["自身故障 → 剔除本测点 + 重要级报警","依赖数据 BAD → 使用其他测点均值","云端断连 → 不受影响，PLC 独立运行"],thresholds:[],behaviors:passive("持续采集环境数据"),points:pts([["temp","温度","REAL","℃","R","10s"],["rh","相对湿度","REAL","%","R","10s"]])},
 co2:{name:"CO₂ 传感器",prefix:"CO2",hint:"空气质量监测",limit:4,defaults:{capacity:0,width:0,height:0,coefficient:0,opening:0},abilities:["读取｜CO₂浓度｜权限：R1以上｜二次确认：否"],dependencies:["影响 → 换气提示与环境报表"],failure:["自身故障 → 剔除本测点 + 重要级报警","依赖数据 BAD → 使用其他测点均值","云端断连 → 不受影响，PLC 独立运行"],thresholds:[],behaviors:passive("持续采集 CO₂ 浓度"),points:pts([["ppm","CO₂浓度","INT","ppm","R","10s"]])}
};
export const kindNames=Object.fromEntries(kinds.map(k=>[k,typeLibrary[k].name])) as Record<Kind,string>;

const overrideSchema=z.object({key:z.string(),value:z.number(),why:z.string().default(""),by:z.string().default(""),date:z.string().default("")});
export const deviceSchema=z.object({id:z.string().min(1).max(80),kind:z.enum(kinds),name:z.string().min(1).max(40),x:z.number().min(8).max(92),y:z.number().min(10).max(88),enabled:z.boolean(),system:z.string().max(40),bus:z.string().max(30),slave:z.string().max(20),register:z.string().max(30),plcAddress:z.string().max(40),plcSync:z.enum(["synced","pending","offline"]),cloudSync:z.enum(["synced","pending","offline"]),open:z.boolean(),opening:z.number().min(0).max(100),capacity:z.number().min(0).max(100000),width:z.number().min(0).max(10),height:z.number().min(0).max(10),coefficient:z.number().min(0).max(1),runtime:z.number().min(0),behaviorOverrides:z.record(z.string(),z.string()).default({}),overrides:z.array(overrideSchema).default([])});
export type Device=z.infer<typeof deviceSchema>;
const ruleSchema=z.object({id:z.string(),metric:z.string(),operator:z.enum(["above","below"]),value:z.number(),duration:z.number().min(0),action:z.string(),releaseValue:z.number(),releaseDuration:z.number().min(0),execution:z.enum(["PLC","云端","仅提示"]).nullable(),priority:z.number().int().min(1).max(5),targetId:z.string(),direction:z.enum(["on","off","neutral"]),scope:z.literal("system")});
export type Rule=z.infer<typeof ruleSchema>;
export const configSchema=z.object({version:z.literal(3),length:z.number().min(10).max(200),width:z.number().min(10).max(150),height:z.number().min(3).max(50),designPressure:z.number().min(180).max(600),loadInterval:z.number().int().min(10).max(180),minDwell:z.number().int().min(10).max(180),observeSeconds:z.number().int().min(10).max(120),rotation:z.enum(["fixed","runtime"]),pressureMode:z.enum(pressureModes),controlMode:z.enum(["auto","manual"]),powerState:z.enum(["mains","generator","none"]),networkState:z.enum(["online","local"]),dataQuality:z.enum(["good","degraded"]),operation:z.enum(["match","training","cleaning","closed"]),events:z.object({door:z.boolean(),ventilation:z.boolean(),environment:z.boolean()}),devices:z.array(deviceSchema).max(80),rules:z.array(ruleSchema).max(30)}).superRefine((c,ctx)=>{if(new Set(c.devices.map(d=>d.id)).size!==c.devices.length)ctx.addIssue({code:"custom",message:"设备编号不能重复"});});
export type Config=z.infer<typeof configSchema>;

export function newDevice(kind:Kind,index:number,id:string,x=50,y=50):Device{const t=typeLibrary[kind],p=t.defaults;return{id,kind,name:t.name+" "+index,x,y,enabled:true,system:"压力维持系统",bus:"Modbus TCP",slave:String(index),register:"自动派生",plcAddress:t.prefix+"_"+String(index).padStart(2,"0"),plcSync:"synced",cloudSync:"synced",open:false,opening:p.opening,capacity:p.capacity,width:p.width,height:p.height,coefficient:p.coefficient,runtime:0,behaviorOverrides:{},overrides:[]};}
const defaults:Array<[Kind,number,number]>= [["vfd",18,80],["vfd",39,80],["gfan",61,80],["gfan",82,80],["dp",31,37],["dp",69,37],["vent",73,12],["vent",87,12],["rev",90,50],["lock",90,66],["cargo",10,50],["emg",10,66],["gen",16,12],["th",38,12],["co2",55,12]];
export const defaultConfig:Config={version:3,length:60,width:30,height:14,designPressure:450,loadInterval:60,minDwell:45,observeSeconds:45,rotation:"fixed",pressureMode:"normal",controlMode:"auto",powerState:"mains",networkState:"online",dataQuality:"good",operation:"training",events:{door:false,ventilation:false,environment:false},devices:defaults.map((d,i)=>newDevice(d[0],defaults.slice(0,i+1).filter(x=>x[0]===d[0]).length,d[0]+"-"+(defaults.slice(0,i+1).filter(x=>x[0]===d[0]).length),d[1],d[2])),rules:[{id:"rule-low-pressure",metric:"膜内差压",operator:"below",value:177,duration:60,action:"加载下一台风机",releaseValue:185,releaseDuration:45,execution:"PLC",priority:1,targetId:"system-fans",direction:"on",scope:"system"}]};

export const targetPressure=(c:Config)=>modeTargets[c.pressureMode];
export const volume=(c:Config)=>c.width*c.length*c.height*.62;
export function ventLimit(mode:PressureMode){return mode==="normal"?35:mode==="wind1"?30:0;}
export function effectiveArea(c:Config){let a=.35;const transientCargo=c.events.door?c.devices.find(d=>d.kind==="cargo"&&d.enabled)?.id:null;for(const d of c.devices){if(!d.enabled)continue;if(d.kind==="rev"||d.kind==="lock")a+=d.width*d.height*d.coefficient;if((d.kind==="cargo"||d.kind==="emg")&&(d.open||d.id===transientCargo))a+=d.width*d.height*d.coefficient;if(d.kind==="vent"){const opening=c.events.ventilation?ventLimit(c.pressureMode):d.opening;a+=.8*Math.min(opening,ventLimit(c.pressureMode))/100;}}return a;}
export function leakFlow(c:Config,p:number){return effectiveArea(c)*.62*Math.sqrt(2*Math.max(p,0)/1.2)*3600;}
export type Log={time:number;text:string;tone:"info"|"warn"};
export type Sim={time:number;pressure:number;nf:number;active:Record<string,boolean>;runtime:Record<string,number>;dwell:Record<string,number>;saturate:number;unload:number;observeUntil:number;supply:number;leak:number;reason:string;events:Log[];trend:number[]};
export function initialSim(c:Config):Sim{return{time:0,pressure:targetPressure(c),nf:16,active:{},runtime:Object.fromEntries(c.devices.filter(d=>d.kind==="vfd"||d.kind==="gfan").map(d=>[d.id,d.runtime])),dwell:{},saturate:0,unload:0,observeUntil:0,supply:0,leak:leakFlow(c,targetPressure(c)),reason:"点击开始模拟，由本地 PLC 顺序投入可用机组。",events:[],trend:[targetPressure(c)]};}
const clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));
function fanOrder(c:Config,s:Sim){const list=c.devices.filter(d=>(d.kind==="vfd"||d.kind==="gfan")&&d.enabled);return c.rotation==="runtime"?[...list].sort((a,b)=>(s.runtime[a.id]??0)-(s.runtime[b.id]??0)||(a.kind==="vfd"?-1:1)):list;}
function bumpless(c:Config,s:Sim,p:number){const on=c.devices.filter(d=>s.active[d.id]&&d.enabled),nv=on.filter(d=>d.kind==="vfd").length,g=on.filter(d=>d.kind==="gfan").length*28000;if(nv)s.nf=clamp((leakFlow(c,p)-g)/(nv*30000)*50,16,50);}
export function tick(c:Config,prev:Sim,dt=1):Sim{const s:Sim={...prev,time:prev.time+dt,active:{...prev.active},runtime:{...prev.runtime},dwell:{...prev.dwell},events:[...prev.events]};const emit=(text:string,tone:Log["tone"]="info")=>s.events.unshift({time:Math.round(s.time),text,tone});const fans=fanOrder(c,s);for(const d of c.devices.filter(x=>x.kind==="vfd"||x.kind==="gfan")){if(!d.enabled&&s.active[d.id]){delete s.active[d.id];emit(d.name+"已检修隔离，退出联动","warn");}if(s.active[d.id]){s.runtime[d.id]=(s.runtime[d.id]??0)+dt/3600;s.dwell[d.id]=(s.dwell[d.id]??0)+dt;}}
 const target=targetPressure(c),forcedStop=c.powerState==="none"||c.pressureMode==="overpressure";if(forcedStop){for(const id of Object.keys(s.active))s.active[id]=false;s.nf=16;s.saturate=s.unload=0;s.reason=c.powerState==="none"?"无电：全部风机停机。":"超压急停：全部风机停机。";}
 else if(c.pressureMode==="wind3"){for(const f of fans){if(!s.active[f.id]){s.active[f.id]=true;s.dwell[f.id]=0;emit("三阶抗风强制投入："+f.name,"warn");}}s.nf=50;s.reason="三阶抗风：全部可用风机满载且禁止停机。";}
 else if(c.controlMode==="manual"){s.reason="手动检修模式：自动加减机暂停。";}
 else if(c.dataQuality==="degraded"){s.nf=42;s.reason="数据质量降级：本地 PLC 固定 42 Hz 运行，云端断连不影响控制。";}
 else {let on=fans.filter(f=>s.active[f.id]);if(!on.length&&fans.length){const first=fans.find(f=>f.kind==="vfd")??fans[0];s.active[first.id]=true;s.dwell[first.id]=0;on=[first];emit("投入首台可用机组："+first.name);}const err=target-s.pressure;s.nf=clamp(s.nf+clamp(err*.14,-2.2,2.2),16,50);const saturated=s.nf>=49.6&&err>3,lowDemand=(s.nf<=16.4&&err<-8)||(s.nf<=25.52&&Math.abs(err)<6);
  if(s.time<s.observeUntil){s.saturate=s.unload=0;s.reason="无扰切换观察期，保持当前机组组合。";}
  else if(saturated){s.saturate+=dt;s.unload=0;const next=fans.find(f=>!s.active[f.id]);s.reason=next?"变频满载且低压，加载计时 "+Math.round(s.saturate)+"/"+c.loadInterval+" 秒。":"全部可用风机已投入，当前泄漏超过装机能力。";if(next&&s.saturate>=c.loadInterval){s.active[next.id]=true;s.dwell[next.id]=0;bumpless(c,s,s.pressure);s.saturate=0;s.observeUntil=s.time+c.observeSeconds;emit("逐台加载："+next.name+"；完成无扰频率预置。",next.kind==="gfan"?"warn":"info");}}
  else if(lowDemand){s.unload+=dt;s.saturate=0;const active=fans.filter(f=>s.active[f.id]);const vfdCount=active.filter(f=>f.kind==="vfd").length;const candidate=[...active].reverse().find(f=>(s.dwell[f.id]??0)>=c.minDwell&&!(f.kind==="vfd"&&vfdCount<=1));if(candidate&&s.unload>=c.loadInterval){const remaining=active.filter(f=>f.id!==candidate.id),capacity=remaining.reduce((n,f)=>n+(f.kind==="vfd"?30000:28000),0);if(capacity>=leakFlow(c,target)*1.05){s.active[candidate.id]=false;bumpless(c,s,s.pressure);s.observeUntil=s.time+c.observeSeconds;emit("逐台卸载："+candidate.name+"；完成无扰频率预置。");}else{s.reason="卸载预判未通过：剩余满载容量不足 5% 余量。";}s.unload=0;}else s.reason="低需求持续，等待满足卸载驻留与计时条件。";}
  else{s.saturate=s.unload=0;s.reason="内环比例调节中；机组台数保持稳定。";}}
 const active=c.devices.filter(d=>d.enabled&&s.active[d.id]);s.supply=active.reduce((n,d)=>n+(d.kind==="vfd"?30000*s.nf/50:d.kind==="gfan"?28000:0),0);s.leak=leakFlow(c,s.pressure);s.pressure=clamp(s.pressure+((s.supply-s.leak)/3600)/volume(c)*2100*dt,0,600);s.trend=[...prev.trend,s.pressure].slice(-240);s.events=s.events.slice(0,120);return s;}

export type Check={id:number;name:string;ok:boolean;detail:string;deviceId?:string};
export function compileChecks(c:Config):Check[]{const rulesExec=c.rules.every(r=>r.execution);const rulesScope=c.rules.every(r=>r.scope==="system");let missing:Device|undefined;for(const d of c.devices){const t=typeLibrary[d.kind];if(pressureModes.some(m=>!(d.behaviorOverrides[m]??t.behaviors[m]))) {missing=d;break;}}const badOverride=c.devices.find(d=>d.overrides.some(o=>{const def=typeLibrary[d.kind].thresholds.find(t=>t.key===o.key);return !def||o.value<def.min||o.value>def.max;}));const badMeta=c.devices.find(d=>d.overrides.some(o=>!o.why.trim()||!o.by.trim()||!o.date));const p=targetPressure(c),needed=leakFlow(c,p)*1.15,capacity=c.devices.filter(d=>d.enabled).reduce((n,d)=>n+(d.kind==="vfd"?30000:d.kind==="gfan"?28000:0),0);const vfdRange=c.devices.filter(d=>d.enabled&&d.kind==="vfd").length*30000*(50-16)/50;return[{id:1,name:"规则执行位置",ok:!!rulesExec,detail:rulesExec?"全部规则已标注 PLC / 云端 / 仅提示":"存在未标注执行位置的规则"},{id:2,name:"状态机边界",ok:rulesScope,detail:rulesScope?"跨设备动作均归属系统对象":"设备状态机引用了其他设备"},{id:3,name:"七工况行为完整",ok:!missing,detail:missing?missing.name+"存在未定义工况":"全部实例的七个压力工况已定义",deviceId:missing?.id},{id:4,name:"阈值与设计荷载",ok:!badOverride&&Math.max(...Object.values(modeTargets))<=c.designPressure,detail:badOverride?badOverride.name+"的覆盖值超出类型区间":"阈值均在类型区间和设计压力内",deviceId:badOverride?.id},{id:5,name:"覆盖变更留痕",ok:!badMeta,detail:badMeta?badMeta.name+"缺少原因、责任人或日期":"所有实例覆盖均有完整留痕",deviceId:badMeta?.id},{id:6,name:"风机容量余量",ok:capacity>=needed,detail:"装机 "+Math.round(capacity).toLocaleString()+" / 最低需求 "+Math.round(needed).toLocaleString()+" m³/h"},{id:7,name:"变频吸收工频梯级",ok:vfdRange>=28000,detail:"变频可调范围 "+Math.round(vfdRange).toLocaleString()+" / 工频梯级 28,000 m³/h"}];}
export function derivedPoints(c:Config){return c.devices.flatMap(d=>typeLibrary[d.kind].points.map((p,i)=>({id:d.plcAddress+"_"+p.suffix,deviceId:d.id,device:d.name,type:typeLibrary[d.kind].name,...p,bus:d.bus,address:d.plcAddress+"."+(i+1),integrity:pressureModes.every(m=>!!(d.behaviorOverrides[m]??typeLibrary[d.kind].behaviors[m]))})));}
